export default [
  {
    type: 'DOCTRINE',
    doctrineId: 1,
    es: 'Dios',
    en: 'God',
  },
  {
    type: 'BELIEF',
    doctrineId: 1,
    beliefId: 1,
    es: 'La Palabra de Dios',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/01.jpg',
  },
  {
    type: 'DECLARATION',
    beliefId: 1,
    order: 1,
    es: 'Las Sagradas Escrituras, que abarcan el Antiguo Testamento y el Nuevo Testamento, constituyen la Palabra de Dios escrita, transmitida por inspiración divina.',
    references: [
      '2 Pedro 1:20-21',
      '2 Timoteo 3:16-17',
      'Proverbios 30:5-6',
      'San Juan 17:17',
      '1 Tesalonicenses 2:13',
    ],
  },
  {
    type: 'DECLARATION',
    beliefId: 1,
    order: 2,
    es: 'Los autores inspirados hablaron y escribieron impulsados por el Espíritu Santo.',
    references: [
      '2 Pedro 1:20-21',
      '2 Timoteo 3:16-17',
      '1 Tesalonicenses 2:13',
    ],
  },
  {
    type: 'DECLARATION',
    beliefId: 1,
    order: 3,
    es: 'Por medio de esta Palabra, Dios comunica a los seres humanos el conocimiento necesario para alcanzar la salvación.',
    references: [
      'Salmos 119:105',
      'San Juan 17:17',
      'Hebreos 4:12',
    ],
  },
  {
    type: 'DECLARATION',
    beliefId: 1,
    order: 4,
    es: 'Las Sagradas Escrituras son la revelación suprema, autoritativa e infalible de la voluntad divina.',
    references: [
      'Proverbios 30:5-6',
      'Isaías 8:20',
      'San Juan 17:17',
      'Hebreos 4:12',
    ],
  },
  {
    type: 'DECLARATION',
    beliefId: 1,
    order: 5,
    es: 'Son la norma del carácter, el criterio para evaluar la experiencia, la revelación definitiva de las doctrinas, un registro fidedigno de los actos de Dios realizados en el curso de la historia.',
    references: [
      '2 Timoteo 3:16-17',
      'Salmos 119:105',
      'Proverbios 30:5-6',
      'Isaías 8:20',
      'San Juan 17:17',
      'Hebreos 4:12',
    ],
  },
  {
    type: 'BELIEF',
    doctrineId: 1,
    beliefId: 2,
    es: 'La Trinidad',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/02.jpg',
  },
  {
    type: 'BELIEF',
    doctrineId: 1,
    beliefId: 3,
    es: 'Dios el Padre',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/03.jpg',
  },
  {
    type: 'BELIEF',
    doctrineId: 1,
    beliefId: 4,
    es: 'Dios el Hijo',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/04.jpg',
  },
  {
    type: 'BELIEF',
    doctrineId: 1,
    beliefId: 5,
    es: 'Dios el Espíritu Santo',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/05.jpg',
  },
  {
    type: 'DOCTRINE',
    doctrineId: 2,
    es: 'La Humanidad',
    en: 'The Human Kind',
  },
  {
    type: 'BELIEF',
    doctrineId: 2,
    beliefId: 6,
    es: 'La creación',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/06.jpg',
  },
  {
    type: 'BELIEF',
    doctrineId: 2,
    beliefId: 7,
    es: 'La naturaleza humana',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/07.jpg',
  },
  {
    es: 'La salvación',
    type: 'DOCTRINE',
    doctrineId: 3,
  },
  {
    type: 'BELIEF',
    doctrineId: 3,
    beliefId: 7,
    es: 'El gran conflicto',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/08.jpg',
  },
  {
    type: 'BELIEF',
    doctrineId: 3,
    beliefId: 9,
    es: 'La vida, muerte y resurrección de Cristo',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/09.jpg',
  },
  {
    type: 'BELIEF',
    doctrineId: 3,
    beliefId: 10,
    es: 'La experiencia de la salvación',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/10.jpg',
  },
  {
    es: 'La iglesia',
    type: 'DOCTRINE',
    doctrineId: 4,
  },
  {
    es: 'Crecer en Cristo',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/11.jpg',
    type: 'BELIEF',
    doctrineId: 4,
    beliefId: 11,
  },
  {
    es: 'La Iglesia',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/12.jpg',
    type: 'BELIEF',
    doctrineId: 4,
    beliefId: 12,
  },
  {
    es: 'El remanente y su misión',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/13.jpg',
    type: 'BELIEF',
    doctrineId: 4,
    beliefId: 13,
  },
  {
    es: 'La unidad en el cuerpo de Cristo',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/14.jpg',
    type: 'BELIEF',
    doctrineId: 4,
    beliefId: 14,
  },
  {
    es: 'El bautismo',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/15.jpg',
    type: 'BELIEF',
    doctrineId: 4,
    beliefId: 15,
  },
  {
    es: 'La Cena del Señor',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/16.jpg',
    type: 'BELIEF',
    doctrineId: 4,
    beliefId: 16,
  },
  {
    es: 'Los dones y ministerios espirituales',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/17.jpg',
    type: 'BELIEF',
    doctrineId: 4,
    beliefId: 17,
  },
  {
    es: 'El don de profecía',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/18.jpg',
    type: 'BELIEF',
    doctrineId: 4,
    beliefId: 18,
  },
  {
    es: 'La vida cristiana',
    type: 'DOCTRINE',
    doctrineId: 5,
  },
  {
    es: 'La ley de Dios',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/19.jpg',
    type: 'BELIEF',
    doctrineId: 5,
    beliefId: 19,
  },
  {
    es: 'El sábado',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/20.jpg',
    type: 'BELIEF',
    doctrineId: 5,
    beliefId: 20,
  },
  {
    es: 'La mayordomía',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/21.jpg',
    type: 'BELIEF',
    doctrineId: 5,
    beliefId: 21,
  },
  {
    es: 'La conducta cristiana',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/22.jpg',
    type: 'BELIEF',
    doctrineId: 5,
    beliefId: 22,
  },
  {
    es: 'El matrimonio y la familia',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/23.jpg',
    type: 'BELIEF',
    doctrineId: 5,
    beliefId: 23,
  },
  {
    es: 'Los acontecimientos finales',
    type: 'DOCTRINE',
    doctrineId: 6,
  },
  {
    es: 'El ministerio de Cristo en el santuario celestial',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/24.jpg',
    type: 'BELIEF',
    doctrineId: 6,
    beliefId: 24,
  },
  {
    es: 'La segunda venida de Cristo',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/25.jpg',
    type: 'BELIEF',
    doctrineId: 6,
    beliefId: 25,
  },
  {
    es: 'La muerte y la resurrección',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/26.jpg',
    type: 'BELIEF',
    doctrineId: 6,
    beliefId: 26,
  },
  {
    es: 'El milenio y el fin del pecado',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/27.jpg',
    type: 'BELIEF',
    doctrineId: 6,
    beliefId: 27,
  },
  {
    es: 'La Tierra Nueva',
    image: 'https://aws-www-es.s3.amazonaws.com/sites/2/2014/03/28.jpg',
    type: 'BELIEF',
    doctrineId: 6,
    beliefId: 28,
  },
  {
    type: 'REFERENCE',
    reference: '2 Pedro 1:20-21',
    rvr95: {
      reference: '2 Pedro 1:20-21',
      verse: 'Pero ante todo entended que ninguna profecía de la Escritura es de interpretación privada, porque nunca la profecía fue traída por voluntad humana, sino que los santos hombres de Dios hablaron siendo inspirados por el Espíritu Santo.',
    },
  },
  {
    type: 'REFERENCE',
    reference: 'Salmos 119:105',
    rvr95: {
      reference: 'Salmos 119:105',
      verse: 'Lámpara es a mis pies tu palabra y lumbrera a mi camino.',
    },
  },
  {
    type: 'REFERENCE',
    reference: 'Proverbios 30:5-6',
    rvr95: {
      reference: 'Proverbios 30:5-6',
      verse: 'Toda palabra de Dios es limpia; él es escudo para los que en él esperan.  No añadas a sus palabras, para que no te reprenda y seas hallado mentiroso.',
    },
  },
  {
    type: 'REFERENCE',
    reference: 'Isaías 8:20',
    rvr95: {
      reference: 'Isaías 8:20',
      verse: '¡A la ley y al testimonio! Si no dicen conforme a esto, es porque no les ha amanecido.',
    },
  },
  {
    type: 'REFERENCE',
    reference: 'San Juan 17:17',
    rvr95: {
      reference: 'San Juan 17:17',
      verse: 'Santifícalos en tu verdad: tu palabra es verdad.',
    },
  },
  {
    type: 'REFERENCE',
    reference: '1 Tesalonicenses 2:13',
    rvr95: {
      reference: '1 Tesalonicenses 2:13',
      verse: 'Por lo cual también nosotros damos gracias a Dios sin cesar, porque cuando recibisteis la palabra de Dios que oísteis de nosotros, la recibisteis no como palabra de hombres, sino según es en verdad, la palabra de Dios, la cual actúa en vosotros los creyentes.',
    },
  },
  {
    type: 'REFERENCE',
    reference: 'Hebreos 4:12',
    rvr95: {
      reference: 'Hebreos 4:12',
      verse: 'La palabra de Dios es viva, eficaz y más cortante que toda espada de dos filos: penetra hasta partir el alma y el espíritu, las coyunturas y los tuétanos, y discierne los pensamientos y las intenciones del corazón.',
    },
  },
]
